### ISSUE TITLE
feat request for posthtml-mso

### ISSUE THREAD

**Issue by Scrum** [posthtml/posthtml-mso#1]
Need to use it in `posthtml-mso`, so this:

```html
<outlook><table><tr><td></outlook>
```

results in this:

```html
<!--[if mso|ie]><table><tr><td><![endif]-->
```

and not in this:

```html
<!--[if mso|ie]><table><tr><td></td></tr></table><![endif]-->
```

**Comment by anikethsaha** [comment]
@Scrum can we support officially a way to override the renderer like it is done for parser ? 

@cossssmin it might be an overhead to implement here instead of `posthtml-render`.  let me know if you need any hand 👍

**Comment by Scrum** [comment]
@anikethsaha 
> can we support officially a way to override the renderer like it is done for parser ?

I don't see any reason why we shouldn't do this, and what do you think is missing in the current render ?

**Comment by anikethsaha** [comment]
> and what do you think is missing in the current render ?

as of now, I couldn't see anything missing. but for cases like this issue, it would be better to have an option. just to increase flexibility. developers can write their own renderer from scratch if they need or they can extend the current one which is done by `posthtml-beautify` and mentioned in the code 
[here](https://github.com/posthtml/posthtml/blob/master/lib/index.js#L84-L90).

**Comment by Scrum** [comment]
The decisions made in `posthtml-beautify` were caused by the fact that the parser didn’t process correctly `Downlevel-revealed`, I have a solution that processes correctly `Downlevel-revealed` and many other problems in the new `@posthtml/parse` but I still can not get together and add it))

But I like the idea of allowing users to set their parser or be able to expand the current

**Comment by Scrum** [comment]
Thoughts for implementation

1. First of all, it is necessary to designate the opening and closing tag

**`from`**
```html
<outlook><div></outlook>
```
**`to`**
```html
<outlook type="open"><div><outlook type="close">
```
thereby we get a tree

```js

[
  {
    tag: "outlook",
    attrs: {type="open"},
    content: [
      {
        tag: "div",
        content: [
          {
            tag: "outlook",
            attrs: {type="close"}
          }
        ]
      }
    ]
  }
]
```

2. mutate the tree in

```js

[
  {
    tag: false,
    attrs: {},
    content: [
      '<!--[if mso|ie]>',
      {
        tag: "div",
        content: [
          {
            tag: false,
            attrs: {},
            content: [
              '<![endif]-->'
            ]
          }
        ]
      }
    ]
  }
]
```

3. accordingly, after rendering

```html
<!--[if mso|ie]><div><![endif]--></div>
```

As far as you remember, there is now access to `tree.source` You can take the source, make the necessary transformations in it, and it’s best to do this in advance, apply all the plugins that you can take `tree.plugins` apply to the transformed source and then apply your method to the resulting tree

**Comment by cossssmin** [comment]
I would definitely not want to force the user into defining opening/closing tags through `type` attributes. This is an implementation detail that they shouldn’t have to care about. 

At point 3) the desired output would be

`<!--[if mso|ie]><div><![endif]-->`

But I suppose I can remove everything after the closing endif 👍

**Comment by Scrum** [comment]
> I would definitely not want to force the user into defining opening/closing tags through `type` attributes. This is an implementation detail that they shouldn’t have to care about.

The notation remains the same for the user, and all the magic described above happens inside.

**Comment by Scrum** [comment]
So far I'm stuck on the fact that such a design

**from**
```html
<outlook>one</outlook>
<outlook>two</outlook>
```
**to**
```html
<outlook type="open">one<outlook type="close">
<outlook type="open">two<outlook type="close">
````

**parse to**
```js
[
  {
    tag: "outlook",
    attrs: {type="open"},
    content: [
        'one',
        {
          tag: "outlook",
          attrs: {type="close"},
          content: [
            {
              tag: "outlook",
              attrs: {type="open"},
              content: [...]
            }
          ]
        }
    ]
  }
]
```

gives a tree too deep a nesting

**Comment by Scrum** [comment]
@cossssmin All attempts were in vain, the absence of a closing tag takes the tree deeper, its presence makes all the content content.

**Comment by Scrum** [comment]
@cossssmin Hi, what was the reason to close this issue?

**Comment by Scrum** [comment]
> Based on your previous comment - if we can still tackle this, my bad 😬

We can, I will try to allocate time for this.

**Comment by Scrum** [comment]
@cossssmin Hi, I think it's worth trying the new option using for `posthtml` new version of render with option [closeas](https://github.com/posthtml/posthtml-render#closeas)
